export {default as Home} from './Main/Index'
export {default as Login} from './Auth/Login/Index'
export {default as Join} from './Auth/Join/Index'
export {default as RoadMap} from './RoadMap/Index'
export {default as Project} from './Project/Index'
export {default as Mentor} from './Mentor/Index'
export {default as Club} from './Club/Index'
export {default as MyPage} from './Auth/MyPage/Index'